### PR TITLE
Add test and refactor player creation route

### PR DESCRIPTION
**Pull request by Phoscur**
Sadly the route is already broken so I cannot start refactoring with a green test.

Also I discovered there is an alias route under /user/ while only /users/create/ works without authentication.

### CODE REVIEW

**Comment by Phoscur** [comment]
Now it somehow fails with
```[INFO] CALL getNewUserId();
[ERROR] PROCEDURE ugamela.getNewUserId does not exist```
Did that route ever work? @mamen

**Comment by mamen** [comment]
It did work, could be i forgot to put the stored procedures into the production-server... But i am currently setting up a mysql-environment within the travis build (see #45 )

**Comment by Phoscur** [comment]
Related #30.
Can be squashed I guess!
TODO Remove console.log and add more test assertions.

**Comment by mamen** [comment]
Sorry that i've butchered your PR, but the build is passing now 😅

**Pull request merged**
